context("General functions")

test_that("Generate FORCE folder structure", {
  forcefolder <- tempdir()
  fldrs <- setFolders(forcefolder)
  expect_equal(fldrs[['tmpfolder']], file.path(forcefolder, 'temp'))
  expect_equal(file.exists(fldrs[['tmpfolder']]),TRUE)
  expect_equal(fldrs[['l1folder']], file.path(forcefolder, 'level1'))
  expect_equal(file.exists(fldrs[['l1folder']]),TRUE)
  expect_equal(fldrs[['l2folder']], file.path(forcefolder, 'level2'))
  expect_equal(file.exists(fldrs[['l2folder']]),TRUE)
  expect_equal(fldrs[['queuefolder']], file.path(forcefolder, 'level1'))
  expect_equal(file.exists(fldrs[['queuefolder']]),TRUE)
  expect_equal(fldrs[['queuefile']], 'queue.txt')
  expect_equal(file.exists(file.path(forcefolder, 'level1/queue.txt')),TRUE)
  expect_equal(fldrs[['demfolder']], file.path(forcefolder, 'misc/dem'))
  expect_equal(file.exists(fldrs[['demfolder']]),TRUE)
  expect_equal(fldrs[['wvpfolder']], file.path(forcefolder, 'misc/wvp'))
  expect_equal(file.exists(fldrs[['wvpfolder']]),TRUE)
  expect_equal(fldrs[['logfolder']], file.path(forcefolder, 'log'))
  expect_equal(file.exists(fldrs[['logfolder']]),TRUE)
  expect_equal(fldrs[['paramfolder']], file.path(forcefolder, 'param'))
  expect_equal(file.exists(fldrs[['paramfolder']]),TRUE)
  expect_equal(fldrs[['paramfile']], 'l2param.prm')
  expect_equal(fldrs[['lcfolder']], file.path(forcefolder, 'misc/lc'))
  expect_equal(file.exists(fldrs[['lcfolder']]),TRUE)
  expect_equal(fldrs[['tcfolder']], file.path(forcefolder, 'misc/tc'))
  expect_equal(file.exists(fldrs[['tcfolder']]),TRUE)
  expect_equal(fldrs[['firefolder']], file.path(forcefolder, 'misc/fire'))
  expect_equal(file.exists(fldrs[['firefolder']]),TRUE)
  expect_equal(fldrs[['S2auxfolder']], file.path(forcefolder, 'misc/S2'))
  expect_equal(file.exists(fldrs[['S2auxfolder']]),TRUE)
  expect_equal(fldrs[['demlogfile']], file.path(forcefolder, 'log/DEM.txt'))
  expect_equal(file.exists(fldrs[['demlogfile']]),TRUE)
  expect_equal(fldrs[['wvplogfile']], file.path(forcefolder, 'log/WVP.txt'))
  expect_equal(file.exists(fldrs[['wvplogfile']]),TRUE)
  expect_equal(fldrs[['landsatlogfile']], file.path(forcefolder, 'log/Landsat.txt'))
  expect_equal(file.exists(fldrs[['landsatlogfile']]),TRUE)
  expect_equal(fldrs[['lclogfile']], file.path(forcefolder, 'log/LC.txt'))
  expect_equal(file.exists(fldrs[['lclogfile']]),TRUE)
  expect_equal(fldrs[['firelogfile']], file.path(forcefolder, 'log/fire.txt'))
  expect_equal(file.exists(fldrs[['firelogfile']]),TRUE)
  expect_equal(fldrs[['tclogfile']], file.path(forcefolder, 'log/tc.txt'))
  expect_equal(file.exists(fldrs[['tclogfile']]),TRUE)
  expect_equal(fldrs[['Sskiplogfile']], file.path(forcefolder, 'log/Sskip.txt'))
  expect_equal(file.exists(fldrs[['Ssuccesslogfile']]),TRUE)
  expect_equal(fldrs[['Ssuccesslogfile']], file.path(forcefolder, 'log/Ssuccess.txt'))
  expect_equal(file.exists(fldrs[['Sskiplogfile']]),TRUE)
  expect_equal(fldrs[['Smissionlogfile']], file.path(forcefolder, 'log/Smission.txt'))
  expect_equal(file.exists(fldrs[['Smissionlogfile']]),TRUE)
  expect_equal(fldrs[['Sotherlogfile']], file.path(forcefolder, 'log/Sother.txt'))
  expect_equal(file.exists(fldrs[['Sotherlogfile']]),TRUE)

  unlink(forcefolder, recursive = T)
})

test_that("Mask raster values outside area of interest", {
  r_empty <- terra::rast(ncol=360, nrow=180)
  m <- r_empty; values(m) <- 1:(360*180)
  ext <- c(-60.4,30.4,-10.2,15.6)
  out <- maskAOI(m, ext)
  expect_equal(as.numeric(out[1,]),rep(0,360))
  expect_equal(as.numeric(out[,1]),rep(0,180))
  expect_equal(as.numeric(out[,125]>0),c(rep(0,74),rep(1,26),rep(0,80)))
  expect_equal(as.numeric(out[90,]>0),c(rep(0,120),rep(1,90),rep(0,150)))
})

test_that("Rollback observations to quarterly frequency", {
  dts <- as.Date(c('2000-02-01','2000-05-01','2000-04-08','2000-09-20'))
  val <- rollback_quart(dts)
  exp <- as.Date(c('2000-01-01','2000-04-01','2000-04-01','2000-07-01'))
  expect_equal(val, exp)
})
